# second_app/docker-compose.yml
version: '3'
services:
  web:
    build: .
    command: gunicorn your_app.wsgi:application --bind 0:8001  # Note different port
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "81:80"    # Note different ports
      - "444:443"  # Note different ports
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: