services:
  web:
    build: .
    container_name: verto-web-1
    command: gunicorn verto.wsgi:application --bind 0:8001
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: verto-db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    build: ./nginx
    container_name: verto-nginx-1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "81:80"  # This will make it accessible at IP:81
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
