FROM python:3.9

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE verto.settings

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

RUN pip install gunicorn

RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "verto.wsgi:application", "--bind", "0.0.0.0:8000"]