# Generated by Django 4.2 on 2024-08-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_nfcproduct_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brand_logos/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='nfcproduct',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
